spring:
  application:
    name: miro-rest
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: ${datasource_url:jdbc:mysql://localhost:3306/miro?useSSL=false}
    username: ${db_user:root}
    password: ${db_password:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: ${db_ddl_auto:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use-jdbc-metadata: false
        ddl_auto: ${db_ddl_auto:none}
        globally_quoted_identifiers: true
    show-sql: false
  sql:
    init:
      platform: mysql
server:
  port: ${app_port:3001}
  servlet:
    context-path: /api/v1
  error:
    include-message: always
miro:
  rest:
    jwtSecret: ${jwt_secret:77397A244326462948404D635166546A576E5A7234753778214125442A472D4B}
    jwtAccessExpirationMs: ${jwt_access_expiration_ms:604800000} # 7 days